# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    -name: fetch your code
     uses: actions/checkout@v4

    -name: login to docker hub
     run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

    -name: build docker image
     run: docker built -t ${{secrets.DOCKER_USERNAME}}/awsdeployment .

    -name: push docker image
     run: docker push  ${{secrets.DOCKER_USERNAME}}/awsdeployment:latest
    

    
